#!/bin/bash
# dnsinkhole - for testing life without dns
# (must be run elevated, with no local dns server)
mv /etc/resolv.conf /etc/resolv.conf-
echo nameserver 127.0.0.1 > /etc/resolv.conf
nc -vlp 53 || mv /etc/resolv.conf- /etc/resolv.conf
